# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS


AWS_BUCKET_DEVELOPMENT: "pet-sitter-development"

AWS_BUCKET_PRODUCTION: "pet-sitter-production"

AWS_ACCESS_KEY_ID: "AKIAIQF7EZOH3FVXA3UA"

AWS_SECRET_ACCESS_KEY: "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"

MAPS_API_KEY: "AIzaSyC3wC9ThJlpDZB6SywMiRnL-oKvWipbAqM"
